# Copyright (c) Robert Bosch GmbH and LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Output Model to Markdown

on:
 push:
#   branches:
#      - main

env:
  ModelName: VacuumCleanerRobotModel.qeax

jobs:
  CreateMarkdown:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0 

      # create LemonTree.Automation License from Actions Secret    
      - name: PrepareLTALicense 
        run: |
            '${{secrets.LTALICENSE}}' | Out-File -FilePath lta.lic    

      # download Lemontree.Automation on a runner and setup the license
      - name: Run LTA on Docker
        run: |
      
          docker run -id --name ltacli -v "$(Get-Location):/data" nexus.lieberlieber.com:5000/lieberlieber/lemontree.automation:latest
          
          docker exec -i ltacli ./lemontree.automation diff --theirs /data/assets/empty.qeax --mine /data/${{env.ModelName}}  --DiffReportFilename "/tmp/DiffReport.xml" --license "/data/lta.lic"
          docker cp ltacli:/tmp/DiffReport.xml /tmp/DiffReport.xml 
          cat /tmp/DiffReport.xml
          
          # docker exec -i ltacli ./lemontree.automation svgexport --Model "/data/${{env.ModelName}}" --diagramdirectory="." --license "/data/lta.lic"

      - name: Archive DiffReport.xml
        uses: actions/upload-artifact@v4
        with:
                  name: DiffReport
                  path: /tmp/DiffReport.xml
                  retention-days: 5

      # - name: Archive svg 
      #   uses: actions/upload-artifact@v4
      #   with:
      #             name: SVGDiagrams
      #             path: .\svg\*.svg
      #             retention-days: 5
          

 
     
    
